services:
  db:
    image: postgres:16-alpine
    container_name: hotel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - hotel_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: hotel_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel_db
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      JWT_SECRET: ${JWT_SECRET:-cambiar-esto-por-una-clave-larga-y-secreta-de-256bits}
    ports:
      - "8080:8080"

volumes:
  hotel_db_data: